[package]
categories = ["library"]
description = "Common code"
edition = "2021"
keywords = ["aws", "aws-lambda", "amazon dynamodb"]
license-file = "../../LICENSE"
readme = "../../README.md"
name = "library"
repository = "https://github.com/JaderDias/aws-activity-pub"
version = "0.1.0"

[lib]
name = "library"
path = "lib.rs"

# Starting in Rust 1.62 you can use `cargo add` to add dependencies 
# to your project.
#
# If you're using an older Rust version,
# download cargo-edit(https://github.com/killercup/cargo-edit#installation) 
# to install the `add` subcommand.
#
# Running `cargo add DEPENDENCY_NAME` will
# add the latest version of a dependency to the list,
# and it will keep the alphabetic ordering for you.

[dependencies]
aws-config = "0.55.0"
aws-sdk-dynamodb = "0.25"
base64 = "0.21.0"
hex = "0.4.3"
http = "0.2.9"
openssl = "0.10.49"
rand = "0.8.5"
regex = "1.7.1"
serde_bytes = "0.11.9"
reqwest = { version = "0.11.14", default-features = false, features = [
    "rustls-tls",
] }
rocket = { version = "0.5.0-rc.3", features = ["json"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_dynamo = { version = "4.2", features = ["aws-sdk-dynamodb+0_25"] }
serde_json = { version = "1.0.93", features = ["raw_value"] }
time = "0.3"
tokio = { version = "1.27", features = ["macros"] }
tracing = { version = "0.1.37" }
tracing-appender = "0.2.2"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.16", default_features = false, features = [
    "env-filter",
] }

[package.metadata.cargo-udeps.ignore]
normal = [
    "tracing-appender",
] # udeps can't detect it, but this dependency is needed
