name: Deploy

on:
  push:
    branches: ["deploy"]

env:
  AWS_REGION: eu-central-1 # set this to your preferred AWS region, e.g. us-west-1
  CARGO_TERM_COLOR: always
  S3_BUCKET: cf-templates-jbywbbl8iz9d-eu-central-1 # needs to be in the same AWS region as the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --workspace --release
      - name: Package
        run: |
          docker-compose -f docker/build/docker-compose.yml up \
                         --exit-code-from amazonlinux2
          mkdir -p dist/dynamodb_stream
          mkdir -p dist/web_service
          cp target/release/web_service dist/web_service/bootstrap
          cp target/release/dynamodb_stream dist/dynamodb_stream/bootstrap
          zip -jr dist/web_service.zip dist/web_service
          zip -jr dist/dynamodb_stream.zip dist/dynamodb_stream
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Upload
        run: |
          DYNAMODB_STREAM_CODE_OBJECT_KEY=$(md5sum dist/dynamodb_stream.zip | cut -d' ' -f1)
          WEB_SERVICE_CODE_OBJECT_KEY=$(md5sum dist/web_service.zip | cut -d' ' -f1)
          aws s3 cp dist/dynamodb_stream.zip "s3://$S3_BUCKET/$DYNAMODB_STREAM_CODE_OBJECT_KEY"
          aws s3 cp dist/web_service.zip "s3://$S3_BUCKET/$WEB_SERVICE_CODE_OBJECT_KEY"
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: rust-lambda
          template: cloudformation.yml
          parameter-overrides: "CodeBucket=${{ env.S3_BUCKET }},DynamodbStreamCodeObjectKey=${{ env.DYNAMODB_STREAM_CODE_OBJECT_KEY }},WebServiceCodeObjectKey=${{ env.WEB_SERVICE_CODE_OBJECT_KEY }}"
